name: Metrics
on:
  schedule: [{ cron: "0 */6 * * *" }]  # 注意：原 cron 表达式末尾有多余空格，已删除！！！
  workflow_dispatch:
  push: {branches: ["main"]}  # 建议统一分支为 `main`

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write  # 必须要有写入权限
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: GGB00M3  # 你的 GitHub 用户名
          # 3D 模板核心配置
          template: profile-3d-contrib
          plugin_3d: yes
          plugin_3d_theme: night-rainbow  # 主题配色
          plugin_3d_animation: yes        # 启用动画
          plugin_3d_frame: stacked        # 3D 框架样式
          # 其他必要参数
          filename: github-3d.svg  # 指定输出文件名（重要！）
          config_timezone: Asia/Shanghai
          # 可以移除不需要的模块（如 base 参数不适用于 3D 模板）
