name: 3D Contribution Metrics
on:
  schedule: 
    - cron: "0 */6 * * *"  # 每6小时运行一次（UTC时间）
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  generate-3d:
    runs-on: ubuntu-latest
    environment: production
    
    permissions:
      contents: write
      actions: read  # 新增推荐权限
      pull-requests: write
    
    steps:
      - name: Generate 3D SVG
        uses: lowlighter/metrics@latest
        with:
          # 认证配置
          token: ${{ secrets.GITHUB_TOKEN || secrets.METRICS_TOKEN }}
          
          # 核心参数
          user: GGB00M3
          template: profile-3d-contrib
          filename: github-3d.svg
          
          # 插件配置
          plugins: 3d
          plugin_3d_theme: night-rainbow
          plugin_3d_animation: true
          plugin_3d_frame: stacked
          
          # 增强配置
          config_timezone: Asia/Shanghai
          cached: true  # 启用缓存
          commits_auto_push: true  # 自动提交文件
          plugin_3d_steps: 64  # 渲染精度
