name: 3D Contribution Metrics
on:
  schedule:
    - cron: "0 */6 * * *"  # 每6小时运行一次UTC时间
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  generate-3d:
    runs-on: ubuntu-latest
    environment: 
      name: production  # 需先在仓库设置中创建该环境
    
    # 正确位置的权限配置
    permissions:
      contents: write
      actions: read
      checks: write
    
    steps:
      - name: Generate 3D SVG
        uses: lowlighter/metrics@latest
        with:
          # 令牌优先级配置
          token: ${{ secrets.GITHUB_TOKEN || secrets.METRICS_TOKEN }}
          
          # 核心配置
          user: GGB00M3
          template: profile-3d-contrib
          filename: github-3d.svg
          
          # 3D插件配置（最新语法）
          plugins: 3d  # 替代旧版 plugin_3d 参数
          plugin_3d_theme: night-rainbow
          plugin_3d_animation: true  # 使用布尔值替代 yes
          plugin_3d_frame: stacked
          
          # 增强配置
          config_timezone: Asia/Shanghai
          cached: true
          plugin_3d_steps: 64
          
          # 推荐增加的缓存配置
          commits_auto_push: true  # 自动提交生成的SVG
